In [1]:
##Problem Statement
##Perform the following operations on the Air Quality Dataset :- 
##Data cleaning , Data integration  , Data Tranformation , Error Correction , Data model building

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_air = pd.read_csv('AirQuality.csv',delimiter=';' , decimal=',')

In [4]:
df_air.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

In [5]:
##DATA CLEANING
df_air.isnull().sum()

Date              114
Time              114
CO(GT)            114
PT08.S1(CO)       114
NMHC(GT)          114
C6H6(GT)          114
PT08.S2(NMHC)     114
NOx(GT)           114
PT08.S3(NOx)      114
NO2(GT)           114
PT08.S4(NO2)      114
PT08.S5(O3)       114
T                 114
RH                114
AH                114
Unnamed: 15      9471
Unnamed: 16      9471
dtype: int64

In [6]:
df_air_clean = df_air.drop(['Unnamed: 15','Unnamed: 16'] , axis=1)

In [7]:
df_air_clean.dropna()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,04/04/2005,10.00.00,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11.00.00,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12.00.00,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13.00.00,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14.00.00,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [8]:
##DATA INTEGRATION
sample_df = df_air_clean.sample(n=200 , random_state=42)

In [9]:
df1 = sample_df[['CO(GT)','C6H6(GT)','NOx(GT)','NO2(GT)' , 'NMHC(GT)']]
df2 = sample_df[['T','RH','AH','NMHC(GT)']]

In [10]:
df1.head()

      CO(GT)  C6H6(GT)  NOx(GT)  NO2(GT)  NMHC(GT)
774      0.7       1.6     41.0     58.0      31.0
4625     2.1      10.2    251.0    115.0    -200.0
6214     3.4      17.4    602.0    160.0    -200.0
6465     1.0       3.0   -200.0   -200.0    -200.0
2362  -200.0       3.3     32.0     51.0    -200.0

In [11]:
df2.head()

         T    RH      AH  NMHC(GT)
774   13.7  38.3  0.5957      31.0
4625  30.0  28.5  1.1883    -200.0
6214  13.7  66.8  1.0432    -200.0
6465  12.2  69.6  0.9860    -200.0
2362  18.8  58.6  1.2581    -200.0

In [12]:
merged_data = pd.merge(df2,df1,on='NMHC(GT)',how='inner')

In [13]:
merged_data

          T    RH      AH  NMHC(GT)  CO(GT)  C6H6(GT)  NOx(GT)  NO2(GT)
0      13.7  38.3  0.5957      31.0     0.7       1.6     41.0     58.0
1      30.0  28.5  1.1883    -200.0     2.1      10.2    251.0    115.0
2      30.0  28.5  1.1883    -200.0     3.4      17.4    602.0    160.0
3      30.0  28.5  1.1883    -200.0     1.0       3.0   -200.0   -200.0
4      30.0  28.5  1.1883    -200.0  -200.0       3.3     32.0     51.0
...     ...   ...     ...       ...     ...       ...      ...      ...
29269  29.5  32.1  1.3005    -200.0     3.6      20.7    234.0    159.0
29270  29.5  32.1  1.3005    -200.0     0.3       2.8    219.0    143.0
29271  29.5  32.1  1.3005    -200.0  -200.0       3.8   -200.0   -200.0
29272  29.5  32.1  1.3005    -200.0  -200.0       4.9   -200.0   -200.0
29273  29.5  32.1  1.3005    -200.0     1.4       8.0     79.0     88.0

[29274 rows x 8 columns]

In [14]:
merged_data.duplicated().sum()

np.int64(1191)

In [15]:
new_merged_data = merged_data.drop_duplicates(['NMHC(GT)'])

In [16]:
# new_merged_data = merged_data.drop_duplicates(['T'])

In [17]:
new_merged_data
new_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 28247
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   T         27 non-null     float64
 1   RH        27 non-null     float64
 2   AH        27 non-null     float64
 3   NMHC(GT)  27 non-null     float64
 4   CO(GT)    27 non-null     float64
 5   C6H6(GT)  27 non-null     float64
 6   NOx(GT)   27 non-null     float64
 7   NO2(GT)   27 non-null     float64
dtypes: float64(8)
memory usage: 2.0 KB

In [18]:
##Error Correction

In [19]:
def remove_outlier(column): 
    column = column.copy()
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3-Q1
    threshold = 1.5*IQR
    outlier_mask = (column<Q1-threshold) | (column>Q3+threshold)
    return column[~outlier_mask]

In [20]:
col_name = ['T','RH','AH', 'NMHC(GT)' , 'CO(GT)','C6H6(GT)','NOx(GT)','NO2(GT)']

In [21]:
for col in col_name:
    new_merged_data.loc[: , col] = remove_outlier(new_merged_data[col])

In [22]:
new_merged_data.reset_index(drop=True , inplace=True)

In [23]:
new_merged_data.fillna(new_merged_data.mean(numeric_only=True))

,T,RH,AH,NMHC(GT),CO(GT),C6H6(GT),NOx(GT),NO2(GT)
0,13.70000,38.300000,0.595700,31.000000,0.700000,1.60,41.00000,58.000000
1,30.00000,28.500000,1.188300,117.818182,2.100000,10.20,251.00000,115.000000
2,24.90000,30.800000,0.954000,117.818182,1.779167,8.25,250.00000,164.000000
3,8.10000,72.100000,0.779800,68.000000,0.800000,2.80,69.00000,62.000000
4,15.00000,46.100000,0.783300,95.000000,1.300000,4.70,73.00000,84.000000
5,12.40000,64.100000,0.920900,70.000000,1.300000,3.90,71.00000,73.000000
6,16.00000,78.500000,1.420900,166.000000,2.600000,12.90,215.00000,109.000000
7,12.30000,65.400000,0.935100,44.000000,1.779167,4.00,66.00000,71.000000
8,12.60000,54.200000,0.788100,87.000000,1.700000,7.60,89.00000,101.000000
9,16.97037,48.792593,0.904411,117.818182,1.779167,8.25,117.37037,93.074074
10,14.50000,35.400000,0.583900,163.000000,2.100000,8.20,108.00000,106.000000
11,13.20000,50.300000,0.757700,168.000000,2.000000,8.20,125.00000,115.000000
12,22.00000,19.000000,0.496900,48.000000,0.900000,3.10,42.00000,46.000000
13,13.30000,53.600000,0.816900,39.000000,0.600000,1.50,45.00000,57.000000
14,11.00000,60.000000,0.786700,80.000000,2.200000,9.20,172.00000,122.000000
15,24.30000,41.800000,1.256100,215.000000,2.000000,11.00,98.00000,95.000000
16,18.90000,40.600000,0.877100,137.000000,1.800000,8.80,99.00000,100.000000
17,12.80000,63.200000,0.928300,17.000000,0.600000,2.00,38.00000,52.000000
18,20.20000,29.200000,0.683000,126.000000,1.800000,7.30,107.00000,90.000000
19,19.70000,45.400000,1.031200,117.818182,4.100000,19.80,194.00000,132.000000
20,14.80000,40.800000,0.681400,50.000000,1.000000,2.70,44.00000,64.000000
21,12.90000,79.700000,1.177400,64.000000,1.100000,3.00,53.00000,54.000000
22,20.00000,45.000000,1.039000,415.000000,3.000000,15.60,188.00000,105.000000
23,27.00000,31.800000,1.117600,205.000000,1.900000,10.70,99.00000,95.000000
24,13.60000,65.300000,1.013600,117.818182,1.779167,20.70,249.00000,139.000000
25,27.30000,30.000000,1.075200,117.818182,3.600000,19.80,178.00000,145.000000
26,8.20000,60.800000,0.665700,26.000000,1.000000,2.60,47.00000,53.000000
27,19.50000,47.500000,1.065300,278.000000,2.500000,12.60,158.00000,106.000000

In [24]:
##DATA TRANSFORMATION
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression , LogisticRegression
from sklearn.metrics import r2_score , confusion_matrix , accuracy_score , mean_squared_error  , mean_absolute_error

new_data = new_merged_data.dropna()

In [25]:
x = new_data.drop(columns=['T'])
y = new_data['T']

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [27]:
scaler=StandardScaler()

In [28]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [29]:
##DATA MODELING
##1. Linear Regression
linearRegression = LinearRegression()

In [30]:
linearRegression.fit(x_train_scaled , y_train)

LinearRegression()

In [31]:
prediction = linearRegression.predict(x_test_scaled)

In [32]:
r2 = r2_score(y_test,prediction)
mse = mean_squared_error(y_test,prediction)
mae = mean_absolute_error(y_test,prediction)
print('R2 SCORE: ' , r2)
print('MSE: ' , mse)
print('MAE: ',mae)
# R² = 1 means the model perfectly predicts the data (100% accuracy).
# R² = 0 means the model doesn't explain anything about the data (no better than just guessing the average value).
# R² negative means the model is doing worse than guessing the average value.

R2 SCORE:  0.8711345949289309
MSE:  3.112047986304291
MAE:  1.7022246445118392

In [33]:
new_data

       T    RH      AH  NMHC(GT)  CO(GT)  C6H6(GT)  NOx(GT)  NO2(GT)
0   13.7  38.3  0.5957      31.0     0.7       1.6     41.0     58.0
3    8.1  72.1  0.7798      68.0     0.8       2.8     69.0     62.0
4   15.0  46.1  0.7833      95.0     1.3       4.7     73.0     84.0
5   12.4  64.1  0.9209      70.0     1.3       3.9     71.0     73.0
6   16.0  78.5  1.4209     166.0     2.6      12.9    215.0    109.0
8   12.6  54.2  0.7881      87.0     1.7       7.6     89.0    101.0
10  14.5  35.4  0.5839     163.0     2.1       8.2    108.0    106.0
11  13.2  50.3  0.7577     168.0     2.0       8.2    125.0    115.0
12  22.0  19.0  0.4969      48.0     0.9       3.1     42.0     46.0
13  13.3  53.6  0.8169      39.0     0.6       1.5     45.0     57.0
14  11.0  60.0  0.7867      80.0     2.2       9.2    172.0    122.0
15  24.3  41.8  1.2561     215.0     2.0      11.0     98.0     95.0
16  18.9  40.6  0.8771     137.0     1.8       8.8     99.0    100.0
17  12.8  63.2  0.9283      17.0     0.6       2.0     38.0     52.0
18  20.2  29.2  0.6830     126.0     1.8       7.3    107.0     90.0
20  14.8  40.8  0.6814      50.0     1.0       2.7     44.0     64.0
21  12.9  79.7  1.1774      64.0     1.1       3.0     53.0     54.0
22  20.0  45.0  1.0390     415.0     3.0      15.6    188.0    105.0
23  27.0  31.8  1.1176     205.0     1.9      10.7     99.0     95.0
26   8.2  60.8  0.6657      26.0     1.0       2.6     47.0     53.0
27  19.5  47.5  1.0653     278.0     2.5      12.6    158.0    106.0